name: spotify_stats_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.4.0
  http: ^1.2.2
  syncfusion_flutter_charts: ^27.1.50
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  mysql_client: ^0.0.27
  mysql1: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
